config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('', include('pages.urls')),
 	path('', include('project.urls')),
 	path('', include('invoice.urls')),
 	path('', include('sellpoint.urls')),
 	path('', include('financialpartners.urls')),
 	path('', include('intranet.urls')),
 	path('', include('magicproseries.urls')),
    path('admin/', admin.site.urls),
]

financialpartners/urls.py
from django.urls import path
from .views import *

app_name = "financialpartners"

urlpatterns = [
	path('socios-prestamistas/', FinancialpartnersList.as_view(), name='financialpartners-list'),
	path('socio-prestamista/agregar/', FinancialpartnersCreate.as_view(), name='financialpartners-add'),
	path('socio-prestamista/ver/<int:pk>/', FinancialpartnersDetail.as_view(), name='financialpartners-detail'),
	path('socio-prestamista/actualizar/<int:pk>/', FinancialpartnersUpdate.as_view(), name='financialpartners-update'),
	path('socio-prestamista/eliminar/<int:pk>/', FinancialpartnersDelete.as_view(), name='financialpartners-delete'),

	path('socio-direccion/<int:pk>/agregar/', AddressCreate.as_view(), name='address-add'),
	path('socio-direccion/actualizar/<int:pk>/', AddressUpdate.as_view(), name='address-update'),
	path('socio-direccion/eliminar/<int:pk>/', AddressDelete.as_view(), name='address-delete'),

	path('socio-dato-fiscal/<int:pk>/agregar/', FiscalDataCreate.as_view(), name='fiscaldata-add'),
	path('socio-dato-fiscal/actualizar/<int:pk>/', FiscalDataUpdate.as_view(), name='fiscaldata-update'),
	path('socio-dato-fiscal/eliminar/<int:pk>/', FiscalDataDelete.as_view(), name='fiscaldata-delete'),

	path('socio-beneficiario/<int:pk>/agregar/', Financialpartners_beneficiarieCreate.as_view(), name='financialpartners_beneficiarie-add'),
	path('socio-beneficiario/actualizar/<int:pk>/', Financialpartners_beneficiarieUpdate.as_view(), name='financialpartners_beneficiarie-update'),
	path('socio-beneficiario/eliminar/<int:pk>/', Financialpartners_beneficiarieDelete.as_view(), name='financialpartners_beneficiarie-delete'),

	path('socio-banco/<int:pk>/agregar/', BankCreate.as_view(), name='bank-add'),
	path('socio-banco/actualizar/<int:pk>/', BankUpdate.as_view(), name='bank-update'),
	path('socio-banco/eliminar/<int:pk>/', BankDelete.as_view(), name='bank-delete'),

	path('socio-archivo/<int:pk>/agregar/', File_userCreate.as_view(), name='file_user-add'),
	path('socio-archivo/actualizar/<int:pk>/', File_userUpdate.as_view(), name='file_user-update'),
	path('socio-archivo/eliminar/<int:pk>/', File_userDelete.as_view(), name='file_user-delete'),

	path('socio-inversion/<int:pk>/agregar/', InvestmentCreate.as_view(), name='investment-add'),
	path('socio-inversion/actualizar/<int:pk>/', InvestmentUpdate.as_view(), name='investment-update'),
	path('socio-inversion/eliminar/<int:pk>/', InvestmentDelete.as_view(), name='investment-delete'),

	path('consulta/qeq/', QEQCreate.as_view(), name='qeq-add'),

	path('financialpartners-api/', financialpartners_api, name='financialpartners_api'),
]

pages/urls.py
from django.urls import path
from .views import *

urlpatterns = [
	path('', landing, name='landing'),
]

financialpartners/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from config.var_local import VAR_LOCAL, VAR_GLOBAL
from mptt.models import MPTTModel, TreeForeignKey
from django.urls import reverse_lazy, reverse
from localflavor.mx.models import MXRFCField, MXZipCodeField, MXCURPField
from django.db.models.signals import m2m_changed
from django.utils import timezone
from invoice.models import FiscalData
from project.models import User, Address, Bank, File_user, History
import datetime
from django.utils.safestring import mark_safe

APP = "financialpartners"

class Clave_Actividad_Economica(models.Model):
	
	codigo = models.CharField('Código de producto o servicio',max_length=120)	
	nombre = models.CharField('Nombre de producto o servicio',max_length=255)

	class Meta:
		default_permissions = ()

	def __str__(self):
		return '[ {0} ] {1}'.format(self.codigo, self.nombre)

	@property
	def string(self):
		return '[ {0} ] {1}'.format(self.codigo, self.nombre)

VERBOSE_NAME = "Socio prestamista"
VERBOSE_NAME_PLURAL = "Socios prestamistas"
MODEL = "financialpartners"
GENDER_NEW = "un nuevo"
GENDER_THIS = "este"

class Financialpartners(User):

	VERBOSE_NAME = VERBOSE_NAME
	VERBOSE_NAME_PLURAL = VERBOSE_NAME_PLURAL
	MODEL = MODEL
	GENDER_NEW = GENDER_NEW
	GENDER_THIS = GENDER_THIS
	APP = APP

	actividad = models.ForeignKey('Clave_Actividad_Economica', on_delete=models.CASCADE, blank=True, null=True, help_text="Actividad económica del socio", verbose_name="")
	reference_number = models.CharField('Identificación del socio', max_length=250, blank=True, null=True, help_text="Si no cuenta con uno el sistema le asiganará un número")

	class Meta:
		default_permissions = ()
		verbose_name = VERBOSE_NAME
		verbose_name_plural = VERBOSE_NAME_PLURAL
		permissions = (
			('can_view_'+ MODEL.lower(), 'Ve lista de '+ VERBOSE_NAME_PLURAL.lower()),
			('can_edit_'+ MODEL.lower(), 'Modifica '+ VERBOSE_NAME_PLURAL.lower()),
			('can_create_'+ MODEL.lower(), 'Crea '+ VERBOSE_NAME_PLURAL.lower()),
			('can_delete_'+ MODEL.lower(), 'Elimina '+ VERBOSE_NAME_PLURAL.lower()),
		)

	def __str__(self):
		return self.visible_username

	def add_text(self):
		return "NUEVO "+ self.VERBOSE_NAME.upper(), "Agregar "+ self.VERBOSE_NAME.lower(), "Crea "+self.GENDER_NEW+" "+ self.VERBOSE_NAME.lower() +" en el sistema"

	def edit_text(self):
		return "EDITAR "+ self.VERBOSE_NAME.upper(), "Editar "+ self.VERBOSE_NAME.lower(), "Edita los datos de "+self.GENDER_THIS+" "+self.VERBOSE_NAME.lower()+" en el sistema"

	def delete_text(self):
		return "ELIMINAR "+ self.VERBOSE_NAME.upper(), "Eliminar "+ self.VERBOSE_NAME.lower(), "Elimina los datos de "+self.GENDER_THIS+" "+self.VERBOSE_NAME.lower(),"Se eliminará "+self.GENDER_THIS+" "+self.VERBOSE_NAME.lower()+" y todos sus datos asociados!"

	def get_absolute_url_list(self):
		return reverse(APP+':'+self.MODEL.lower()+'-list')+'?module=financialpartners'

	def get_absolute_url_add(self):
		return reverse(APP+':'+self.MODEL.lower()+'-add')+'?module=financialpartners'

	def get_absolute_url_detail(self):
		return reverse(APP+':'+self.MODEL.lower()+'-detail',kwargs={'pk': self.pk})+'?module=financialpartners'

	def get_absolute_url_update(self):
		return reverse(APP+':'+self.MODEL.lower()+'-update',kwargs={'pk': self.pk})+'?module=financialpartners'

	def get_absolute_url_delete(self):
		return reverse(APP+':'+self.MODEL.lower()+'-delete',kwargs={'pk': self.pk})+'?module=financialpartners'

	def rfcs(self):
		p = ''
		for obj in self.my_fiscaldata().all():
			p += obj.rfc + ', '
		return p[0:len(p)-2]

	def string(self):
		return mark_safe("""
				{0} {1}<br > 
				Email:{2}<br /> 
				# Referencia: <strong>{7}</strong><br /> 
				Actividad comercial: {6} <br />
				Nacionalidad:{3}<br /> 
				Fecha de nacimiento: {4}<br /> 
				Género: {5} <br />  
			""".format(
				self.first_name, 
				self.last_name,
				self.email,
				self.country,
				self.birthday,
				self.gender,
				self.actividad,
				self.reference_number,
			)
		) 

	def my_address(self):
		return Address.objects.filter(user = self)

	def my_fiscaldata(self):
		return FiscalData.objects.filter(user = self)

	def my_financialpartners_beneficiaries(self):
		return Financialpartners_beneficiarie.objects.filter(user = self)

	def my_banks(self):
		return Bank.objects.filter(user = self)

	def my_files(self):
		return File_user.objects.filter(user = self, module__code='financialpartners')

	def my_investments(self):
		return Investment.objects.filter(user = self)

VERBOSE_NAME = "Beneficiario"
VERBOSE_NAME_PLURAL = "Beneficiarios"
MODEL = "Financialpartners_beneficiarie"
GENDER_NEW = "un nuevo"
GENDER_THIS = "este"

class Financialpartners_beneficiarie(models.Model):

	VERBOSE_NAME = VERBOSE_NAME
	VERBOSE_NAME_PLURAL = VERBOSE_NAME_PLURAL
	MODEL = MODEL
	GENDER_NEW = GENDER_NEW
	GENDER_THIS = GENDER_THIS
	APP = APP

	user = models.ForeignKey('Financialpartners', on_delete=models.CASCADE)
	name = models.CharField('Nombre completo del beneficiario',max_length=250)
	relationship = models.CharField('Parentesco con el socio',max_length=250)
	percentage = models.IntegerField('Porcentaje %')

	active = models.BooleanField(default=True)

	class Meta:
		default_permissions = ()
		verbose_name = VERBOSE_NAME
		verbose_name_plural = VERBOSE_NAME_PLURAL
		permissions = (
			('can_view_'+ MODEL.lower(), 'Ve lista de '+ VERBOSE_NAME_PLURAL.lower()),
			('can_edit_'+ MODEL.lower(), 'Modifica '+ VERBOSE_NAME_PLURAL.lower()),
			('can_create_'+ MODEL.lower(), 'Crea '+ VERBOSE_NAME_PLURAL.lower()),
			('can_delete_'+ MODEL.lower(), 'Elimina '+ VERBOSE_NAME_PLURAL.lower()),
		)

	def __str__(self):
		return self.name

	def string(self):
		return mark_safe('({0}) <strong>{1}</strong> con el {2}%'.format(self.relationship, self.name, self.percentage))


VERBOSE_NAME = "Inversion"
VERBOSE_NAME_PLURAL = "Inversiones"
MODEL = "investment"
GENDER_NEW = "una nueva"
GENDER_THIS = "esta"

class Investment(models.Model):

	VERBOSE_NAME = VERBOSE_NAME
	VERBOSE_NAME_PLURAL = VERBOSE_NAME_PLURAL
	MODEL = MODEL
	GENDER_NEW = GENDER_NEW
	GENDER_THIS = GENDER_THIS
	APP = APP

	user = models.ForeignKey('Financialpartners', on_delete=models.CASCADE)
	creation_date = models.DateTimeField(auto_now_add=True)

	tipo = models.CharField('Tipo de inversión', max_length=250)
	importe = models.FloatField('Importe de la inversión')
	moneda = models.CharField('Tipo de cambio', max_length=250, default="MXN")
	tasa = models.FloatField('Tasa %')
	tiie = models.FloatField('Tiie %')
	plazo = models.IntegerField('Plazo de la inversión')
	fechaven = models.DateField('Fecha de vencimiento', blank=True, null=True)    
	fechavencon = models.DateField('Fecha de vencimiento del contrato', blank=True, null=True)   
	fechafirmacon = models.DateField('Fecha de confirmación del crédito', blank=True, null=True)   
	periodicidad = models.IntegerField('Peridicidad en meses')
	fechapagocap = models.DateField('Fecha pago a capital', blank=True, null=True)
	estatus = models.CharField('Estatus de la inversión', max_length=250, default="MXN")
	renovacion = models.DateField('Renovación', blank=True, null=True)

	active = models.BooleanField(default=True)

	class Meta:
		default_permissions = ()
		verbose_name = VERBOSE_NAME
		verbose_name_plural = VERBOSE_NAME_PLURAL
		permissions = (
			('can_view_'+ MODEL.lower(), 'Ve lista de '+ VERBOSE_NAME_PLURAL.lower()),
			('can_edit_'+ MODEL.lower(), 'Modifica '+ VERBOSE_NAME_PLURAL.lower()),
			('can_create_'+ MODEL.lower(), 'Crea '+ VERBOSE_NAME_PLURAL.lower()),
			('can_delete_'+ MODEL.lower(), 'Elimina '+ VERBOSE_NAME_PLURAL.lower()),
		)

	def __str__(self):
		return self.name

	def string(self):
		return mark_safe('{0}'.format(self.pk,))



QEQ_PERSONA = (
	('Persona','Persona'),
	('Empresa','Empresa'),
)

VERBOSE_NAME = "Consulta QEQ"
VERBOSE_NAME_PLURAL = "Consultas QEQ"
MODEL = "qeq"
GENDER_NEW = "una nueva"
GENDER_THIS = "esta"

class QEQ(models.Model):

	VERBOSE_NAME = VERBOSE_NAME
	VERBOSE_NAME_PLURAL = VERBOSE_NAME_PLURAL
	MODEL = MODEL
	GENDER_NEW = GENDER_NEW
	GENDER_THIS = GENDER_THIS
	APP = APP

	tipo = models.CharField(choices=QEQ_PERSONA, max_length=100, default='Persona', verbose_name='', help_text='Tipo de persona')
	rfc = MXRFCField(verbose_name="RFC", blank=True, null=True)
	name = models.CharField('Nombre de persona', max_length=100, blank=True, null=True)
	first_name = models.CharField('Apellido paterno', max_length=100, blank=True, null=True)
	last_name = models.CharField('Apellido materno', max_length=100, blank=True, null=True)
	curp = MXCURPField('C.U.R.P.', blank=True, null=True)
	issste = models.CharField('ISSSTE', max_length=100, blank=True, null=True)
	imss = models.CharField('IMSS', max_length=100, blank=True, null=True)
	razon = models.CharField('Razon social', max_length=100, blank=True, null=True)

	class Meta:
		default_permissions = ()
		verbose_name = VERBOSE_NAME
		verbose_name_plural = VERBOSE_NAME_PLURAL
		permissions = (
			('can_view_'+ MODEL.lower(), 'Realiza consultas de '+ VERBOSE_NAME_PLURAL.lower()),
		)

	def __str__(self):
		return self.pk


class History_Financialpartners(History):

	VERBOSE_NAME = VERBOSE_NAME
	VERBOSE_NAME_PLURAL = VERBOSE_NAME_PLURAL
	MODEL = MODEL
	GENDER_NEW = GENDER_NEW
	GENDER_THIS = GENDER_THIS
	APP = APP

	financialpartners = models.ForeignKey('Financialpartners', on_delete=models.CASCADE)

	def __str__(self):
		return self.financialpartners.first_name

financialpartners/forms.py
# -*- encoding: utf-8 -*-
from django import forms
from django.forms import widgets
from project.forms import MaterialCheckboxWidget, MaterialDateWidget, MaterialTextWidget, SelectWidget, SelectMultipleWidget, MaterialColorWidget, BaseUserForm, MaterialDateWidget
from project.models import User, Address, Bank, File_user
from invoice.models import FiscalData
from .models import *

class FinancialpartnersForm(forms.ModelForm):
	class Meta:
		model = Financialpartners
		fields = 'first_name', 'last_name', 'email', 'actividad', 'birthday', 'gender', 'country', 'reference_number'
		labels = {
			'first_name':'Nombre(s) del socio',
			'last_name':'Apellidos del socio',
			'birthday':'Fecha de nacimiento',
			'gender':'',
			'country':'',
			'reference_number':'Numero de referencia del socio',
		}
		help_texts = {
			'gender':'Genero',
			'country':'Pais de origen',
		}
		widgets={
			'actividad':SelectWidget(attrs={'class':'select2',}),
			'country':SelectWidget(attrs={'class':'select2',}),
			'gender':SelectWidget(attrs={'class':'select2',}),
		}


class AddressForm(forms.ModelForm):
	class Meta:
		model = Address
		fields = 'name', 'calle','numero_exterior','numero_interior','colonia','municipio_delegacion','estado','codigo_postal','pais','notes'
		widgets={
			'estado':SelectWidget(attrs={'class':'select2',}),
			'pais':SelectWidget(attrs={'class':'select2',}),
		}


class FiscalDataForm(forms.ModelForm):
	class Meta:
		model = FiscalData
		fields = 'persona','rfc','razon_social','curp','telefono','contacto','email_contacto','calle','numero_exterior','numero_interior','colonia','localidad','municipio_delegacion','estado','codigo_postal','pais',
		widgets={
			'persona':SelectWidget(attrs={'v-model':'persona'}),
			'estado':SelectWidget(attrs={'class':'select2',}),
		}

class Financialpartners_beneficiarieForm(forms.ModelForm):
	class Meta:
		model = Financialpartners_beneficiarie
		fields = 'name','relationship','percentage',

class BankForm(forms.ModelForm):
	class Meta:
		model = Bank
		fields = 'banco','no_cuenta','sucursal','clabe','no_cuenta_habiente'

class FileForm(forms.ModelForm):
	class Meta:
		model = File_user
		fields = 'code','file','name'

class InvestmentForm(forms.ModelForm):
	class Meta:
		model = Investment
		fields = 'tipo','importe','moneda','tasa','tiie','plazo','periodicidad','estatus','renovacion','fechaven','fechavencon','fechafirmacon','fechapagocap'
		widgets={
			'fechaven':MaterialDateWidget(attrs={'class':'date-picker','data-date-format':'d/m/Y'}),
			'fechavencon':MaterialDateWidget(attrs={'class':'date-picker','data-date-format':'d/m/Y'}),
			'fechafirmacon':MaterialDateWidget(attrs={'class':'date-picker','data-date-format':'d/m/Y'}),
			'fechapagocap':MaterialDateWidget(attrs={'class':'date-picker','data-date-format':'d/m/Y'}),
		}

class QEQForm(forms.ModelForm):
	class Meta:
		model = QEQ
		fields = 'tipo','rfc','name','first_name','last_name','curp','issste','imss','razon'
		widgets={
			'tipo':SelectWidget(attrs={'v-model':'tipo'}), #se quito el select2 porque no hace el cambio en vue
			'rfc':MaterialTextWidget(attrs={'v-model':'rfc'}),
			'name':MaterialTextWidget(attrs={'v-model':'name'}),
			'first_name':MaterialTextWidget(attrs={'v-model':'first_name'}),
			'last_name':MaterialTextWidget(attrs={'v-model':'last_name'}),
			'curp':MaterialTextWidget(attrs={'v-model':'curp'}),
			'issste':MaterialTextWidget(attrs={'v-model':'issste'}),
			'imss':MaterialTextWidget(attrs={'v-model':'imss'}),
			'razon':MaterialTextWidget(attrs={'v-model':'razon'}),
		}

financialpartners/templates/financialpartners_detail.html
{% extends "generic/detail.html" %}
{% load static%}
{% load crispy_forms_tags %}
{% load app_tags%}
{% load app_financialpartners%}

{%block pre_css%}
    <style>
        {% include "includes/sellpoint_vendor_styleticket.html" with sellpoint=object%}
    </style>
{%endblock%}

{%block more_options%}
{%endblock%}

{%block detail_grid%}
    <div class="grid-margins-items" size="2">
        <div class="stats__item">
            <div class="stats__chart bg-default">
                <h2 class="color-1 fs-18 mb-0">DATOS DEL SOCIO</h2>
            </div>
            <div class="stats__info">
                <div class="row stats grid">
                    <div class="grid-item">
                        <div class="listview listview--inverse listview--striped">
                            <div class="listview__item lh-9">
                                <div class="widget-past-days__info">
                                    <h3 class="color-default fs-14 mb-0">{{object.string}}</h3>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <a  name="form" class="btn waves-effect bg-color-default color-1 mb-20"><i class="fa fa-file"></i> GENERAR ESTADO DE CUENTA </a>
            </div>
        </div>
    </div>
    <div class="grid-margins-items" size="2">
        <div class="stats__item">
            <div class="stats__chart bg-default">
                <h2 class="color-1 fs-18 mb-0">DATOS FISCALES</h2>
            </div>
            <div class="stats__info">
                <div class="row stats grid">
                    <div class="grid-item">
                        <div class="listview listview--inverse listview--striped">
                            {%for obj in object.my_fiscaldata%}
                                <div class="listview__item lh-9">
                                    <div class="widget-past-days__info">
                                        <h3 class="color-default fs-14 mb-0">
                                            {{obj.string}} 
                                            <span class="color-{%if obj|qeq_rfc%}danger{%else%}success{%endif%}">
                                                <i class="fa fa-circle"></i>
                                            </span>
                                        </h3>
                                        <small class="color-5 mt-3 fs-9"></small>
                                    </div>
                                </div>
                            {%endfor%}
                        </div>
                    </div>
                </div>
                <a href="{% url 'financialpartners:fiscaldata-add' object.pk %}" name="form" class="btn waves-effect bg-color-default color-1 mb-20"><i class="fa fa-plus"></i> AGREGAR </a>
            </div>
        </div>
    </div>
     <div class="grid-margins-items" size="2">
        <div class="stats__item">
            <div class="stats__chart bg-default">
                <h2 class="color-1 fs-18 mb-0">DIRECCIONES</h2>
            </div>
            <div class="stats__info">
                <div class="row stats grid">
                    <div class="grid-item">
                        <div class="listview listview--inverse listview--striped">
                            {%for obj in object.my_address%}
                                <div class="listview__item lh-9">
                                    <div class="widget-past-days__info">
                                        <h3 class="color-default fs-14 mb-0">{{obj}}</h3>
                                        <small class="color-5 mt-3 fs-9"></small>
                                    </div>
                                </div>
                            {%endfor%}
                        </div>
                    </div>
                </div>
                <a href="{% url 'financialpartners:address-add' object.pk %}" name="form" class="btn waves-effect bg-color-default color-1 mb-20"><i class="fa fa-plus"></i> AGREGAR </a>
            </div>
        </div>
    </div>
    
    <div class="grid-margins-items" size="2">
        <div class="stats__item">
            <div class="stats__chart bg-default">
                <h2 class="color-1 fs-18 mb-0">BENEFICIARIOS</h2>
            </div>
            <div class="stats__info">
                <a href="{% url 'financialpartners:financialpartners_beneficiarie-add' object.pk %}" name="form" class="btn waves-effect bg-color-default color-1"><i class="fa fa-plus"></i> AGREGAR </a>
                <div class="row stats grid">
                    <div class="grid-item">
                        <div class="listview listview--inverse listview--striped">
                            {%for obj in object.my_financialpartners_beneficiaries%}
                                <div class="listview__item lh-9">
                                    <div class="widget-past-days__info">
                                        <h3 class="color-default fs-14 mb-0">{{obj.string}}</h3>
                                        <small class="color-5 mt-3 fs-9"></small>
                                    </div>
                                </div>
                            {%endfor%}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="grid-margins-items" size="2">
        <div class="stats__item">
            <div class="stats__chart bg-default">
                <h2 class="color-1 fs-18 mb-0">BANCOS</h2>
            </div>
            <div class="stats__info">
                <a href="{% url 'financialpartners:bank-add' object.pk %}" name="form" class="btn waves-effect bg-color-default color-1"><i class="fa fa-plus"></i> AGREGAR </a>
                <div class="row stats grid">
                    <div class="grid-item">
                        <div class="listview listview--inverse listview--striped">
                            {%for obj in object.my_banks%}
                                <div class="listview__item lh-9">
                                    <div class="widget-past-days__info">
                                        <h3 class="color-default fs-14 mb-0">{{obj.string}}</h3>
                                        <small class="color-5 mt-3 fs-9"></small>
                                    </div>
                                </div>
                            {%endfor%}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="grid-margins-items" size="2">
        <div class="stats__item">
            <div class="stats__chart bg-default">
                <h2 class="color-1 fs-18 mb-0">HISTORIAL</h2>
            </div>
            <div class="stats__info">
                <div class="row stats grid">
                    <div class="grid-item">
                        <div class="listview listview--inverse listview--striped">
                            <div class="listview__item lh-9">
                                <div class="widget-past-days__info">
                                    <h3 class="color-default fs-14 mb-0">Este usuario no tiene historial de cambios</h3>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="grid-margins-items" size="2">
        <div class="stats__item">
            <div class="stats__chart bg-default">
                <h2 class="color-1 fs-18 mb-0">ARCHIVOS</h2>
            </div>
            <div class="stats__info">
                <a href="{% url 'financialpartners:file_user-add' object.pk %}" name="form" class="btn waves-effect bg-color-default color-1"><i class="fa fa-plus"></i> AGREGAR </a>
                <div class="row stats grid">
                    <div class="grid-item">
                        <div class="listview listview--inverse listview--striped">
                            {%for obj in object.my_files%}
                                <div class="listview__item lh-9">
                                    <div class="widget-past-days__info">
                                        <h3 class="color-default fs-14 mb-0">{{obj.string}}</h3>
                                        <small class="color-5 mt-3 fs-9"></small>
                                    </div>
                                </div>
                            {%endfor%}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="grid-margins-items" size="2">
        <div class="stats__item">
            <div class="stats__chart bg-default">
                <h2 class="color-1 fs-18 mb-0">INVERSIONES</h2>
            </div>
            <div class="stats__info">
                <a href="{% url 'financialpartners:investment-add' object.pk %}" name="form" class="btn waves-effect bg-color-default color-1"><i class="fa fa-plus"></i> AGREGAR </a>
                <div class="row stats grid">
                    <div class="grid-item">
                        <div class="listview listview--inverse listview--striped">
                            {%for obj in object.my_investments%}
                                <div class="listview__item lh-9">
                                    <div class="widget-past-days__info">
                                        <h3 class="color-default fs-14 mb-0">{{obj.string}}</h3>
                                        <small class="color-5 mt-3 fs-9"></small>
                                    </div>
                                </div>
                            {%endfor%}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{%endblock detail_grid%}

{%block js%}
    {{ block.super }}
    <script src="{%static 'vendors/jsbarcode/dist/JsBarcode.all.min.js'%}"></script>
{%endblock js%}

{%block extend_vue_Data%}
    ticket: [],
    sellpoint: [],
{%endblock extend_vue_Data%}

{%block extend_vue_methods%}
    {{ block.super }}
{%endblock extend_vue_methods%}

{%block vue_filters%}
{%endblock vue_filters%}

{%block extend_vue_mounted%}
{%endblock extend_vue_mounted%}

financialpartners/templates/financialpartners_list.html
{% extends "generic/list.html" %}
{% load static%}

{%block list%}
    <thead>
        <tr>
            <th>ID</th>
            <th>NOMBRE</th>
            <th>APELLIDOS</th>
            <th>EMAIL</th>
            <th>RFC</th>
        </tr>
    </thead>
    <tbody>
        {%for obj in object_list%}
            <tr>
                <td><a href="{{obj.get_absolute_url_detail}}" class="color-default">{{obj.reference_number}}</a></td>
                <td><a href="{{obj.get_absolute_url_detail}}" class="color-default">{{obj.first_name}}</a></td>
                <td><a href="{{obj.get_absolute_url_detail}}" class="color-default">{{obj.last_name}}</a></td>
                <td><a href="{{obj.get_absolute_url_detail}}" class="color-default">{{obj.email}}</a></td>
                <td><a href="{{obj.get_absolute_url_detail}}" class="color-default">{{obj.rfcs|default:'-'}}</a></td>
            </tr>
        {%endfor%}
    </tbody>
{%endblock list%}s