config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('', include('pages.urls')),
 	path('', include('project.urls')),
 	path('', include('invoice.urls')),
 	path('', include('sellpoint.urls')),
 	path('', include('financialpartners.urls')),
 	path('', include('intranet.urls')),
 	path('', include('magicproseries.urls')),
    path('admin/', admin.site.urls),
]

invoice/urls.py
from django.urls import path
from .views import *
from django_pdfkit import PDFView

app_name = "invoice"

urlpatterns = [

   path('datos-fiscales/', FiscalDataList.as_view(), name='fiscaldata-list'),
   path('datos-fiscales/agregar/', FiscalDataCreate.as_view(), name='fiscaldata-add'),
   path('datos-fiscales/ver/<int:pk>/', FiscalDataDetail.as_view(), name='fiscaldata-detail'),
   path('datos-fiscales/actualizar/<int:pk>/', FiscalDataUpdate.as_view(), name='fiscaldata-update'),
   path('datos-fiscales/eliminar/<int:pk>/', FiscalDataDelete.as_view(), name='fiscaldata-delete'),

   path('facturar-ticket-de-compra/', invoice_ticket, name='invoice_ticket'),

   path('cfdi/', PDFView.as_view(template_name='cfdi.html'), name='cfdi'),
   path('cfdi2/', cfdi2, name='cfdi2'),

]

magicproseries/invoice/urls.py
from django.urls import path
from .views import *
from django_pdfkit import PDFView

app_name = "invoice"

urlpatterns = [

   path('datos-fiscales/', FiscalDataList.as_view(), name='fiscaldata-list'),
   path('datos-fiscales/agregar/', FiscalDataCreate.as_view(), name='fiscaldata-add'),
   path('datos-fiscales/ver/<int:pk>/', FiscalDataDetail.as_view(), name='fiscaldata-detail'),
   path('datos-fiscales/actualizar/<int:pk>/', FiscalDataUpdate.as_view(), name='fiscaldata-update'),
   path('datos-fiscales/eliminar/<int:pk>/', FiscalDataDelete.as_view(), name='fiscaldata-delete'),

   path('facturar-ticket-de-compra/', invoice_ticket, name='invoice_ticket'),

   path('cfdi/', PDFView.as_view(template_name='cfdi.html'), name='cfdi'),
   path('cfdi2/', cfdi2, name='cfdi2'),

]

pages/urls.py
from django.urls import path
from .views import *

urlpatterns = [
	path('', landing, name='landing'),
]

invoice/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from config.var_local import VAR_LOCAL, VAR_GLOBAL
from mptt.models import MPTTModel, TreeForeignKey
from django.urls import reverse_lazy, reverse
from localflavor.mx.models import MXRFCField, MXZipCodeField, MXCURPField
import datetime
from django.db.models.signals import m2m_changed
from djmoney.money import Money
from django.utils import timezone
from django.conf import settings
import OpenSSL.crypto
from lxml.etree import Element, SubElement, QName, tostring, XML, XMLParser, fromstring
import xmltodict
from django.template.loader import render_to_string
from numbertoletters import number_to_letters
from django.utils.safestring import mark_safe
import os
import boto3
import zeep
import pdfkit
import json
from django.core.mail import EmailMultiAlternatives
from django.template import Context, Template
from django.template.loader import get_template

APP = "invoice"

PERSONA = (
    ('Física','Física'),
    ('Moral','Moral'),
)

STATE_CHOICES = (
    ('Aguascalientes', ('Aguascalientes')),
    ('Baja California', ('Baja California')),
    ('Baja California Sur', ('Baja California Sur')),
    ('Campeche', ('Campeche')),
    ('Chihuahua', ('Chihuahua')),
    ('Chiapas', ('Chiapas')),
    ('Coahuila', ('Coahuila')),
    ('Colima', ('Colima')),
    ('CDMX', ('CDMX')),
    ('Durango', ('Durango')),
    ('Guerrero', ('Guerrero')),
    ('Guanajuato', ('Guanajuato')),
    ('Hidalgo', ('Hidalgo')),
    ('Jalisco', ('Jalisco')),
    ('Estado de México', ('Estado de México')),
    ('Michoacán', ('Michoacán')),
    ('Morelos', ('Morelos')),
    ('Nayarit', ('Nayarit')),
    ('Nuevo León', ('Nuevo León')),
    ('Oaxaca', ('Oaxaca')),
    ('Puebla', ('Puebla')),
    ('Querétaro', ('Querétaro')),
    ('Quintana Roo', ('Quintana Roo')),
    ('Sinaloa', ('Sinaloa')),
    ('San Luis Potosí', ('San Luis Potosí')),
    ('Sonora', ('Sonora')),
    ('Tabasco', ('Tabasco')),
    ('Tamaulipas', ('Tamaulipas')),
    ('Tlaxcala', ('Tlaxcala')),
    ('Veracruz', ('Veracruz')),
    ('Yucatán', ('Yucatán')),
    ('Zacatecas', ('Zacatecas')),
)

FiscalData_estatus = (
    ('success','Bien'),
    ('danger','Error'),
    ('warning','Advertencia'),
)

FormaPago = (
    ('01','Efectivo'),
    ('02','Cheque nominativo'),
    ('03','Transferencia electrónica de fondos'),
)

RegimenFiscal = (
    ('601','General de Ley Personas Morales'),
    ('603','Personas Morales con Fines no Lucrativos'),
    ('605','Sueldos y Salarios e Ingresos Asimilados'),
)

def path_cfdi_company(self, filename):
    date = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    file_name = filename.split(".")
    if settings.VAR_PRODUCTION['PRODUCTION']:
        upload_to = "companys/%s_%s/certificados/%s/%s.%s" % (self.company.id, self.company.name, self.rfc, self.rfc, file_name[len(file_name)-1])
    else:
        upload_to = settings.MEDIA_URL+"companys/%s_%s/certificados/%s/%s.%s" % (self.company.id, self.company.name, self.rfc, self.rfc, file_name[len(file_name)-1])
    return upload_to

VERBOSE_NAME = "Información fiscal"
VERBOSE_NAME_PLURAL = "Datos fiscales"
MODEL = "FiscalData"
GENDER_NEW = "nueva"
GENDER_THIS = "este"

class FiscalData(models.Model):

    VERBOSE_NAME = VERBOSE_NAME
    VERBOSE_NAME_PLURAL = VERBOSE_NAME_PLURAL
    MODEL = MODEL
    GENDER_NEW = GENDER_NEW
    GENDER_THIS = GENDER_THIS
    APP = APP

    company = models.ForeignKey('project.Company', related_name='+', on_delete=models.CASCADE, verbose_name="")
    user = models.ForeignKey('project.User', related_name='+', on_delete=models.CASCADE, verbose_name="", blank=True, null=True)

    rfc = MXRFCField(verbose_name="RFC", blank=True, null=True)
    razon_social = models.CharField(verbose_name='', max_length=255, blank=True, null=True, help_text="Razon social de persona Física o Moral")
    persona = models.CharField(choices=PERSONA, max_length=100, blank=True, null=True, verbose_name='', help_text='Tipo de persona', default='Física')
    curp = MXCURPField('C.U.R.P.', blank=True, null=True)
    telefono = models.CharField('Teléfono de contacto', max_length=100, blank=True, null=True)
    contacto = models.CharField('Nombre completo del contacto', max_length=255, blank=True, null=True)
    email_contacto = models.EmailField('Email del contacto', max_length=100, blank=True, null=True)
    calle = models.CharField(max_length=255, blank=True, null=True)
    numero_exterior = models.CharField(max_length=150, blank=True, null=True)
    numero_interior = models.CharField(max_length=150, blank=True, null=True)
    colonia = models.CharField(max_length=255, blank=True, null=True)
    localidad = models.CharField(max_length=255, blank=True, null=True)
    municipio_delegacion = models.CharField('Municipio o Delegación', max_length=150, blank=True, null=True)
    estado = models.CharField(choices=STATE_CHOICES, max_length=100, blank=True, null=True, verbose_name='', help_text='Estado')
    codigo_postal = MXZipCodeField('Código Postal', blank=True, null=True)
    pais = models.CharField(max_length=100, default='México')

    cer = models.FileField('',blank=True, null=True, help_text='.cer certificado generado atravez del CSD', upload_to=path_cfdi_company)
    key = models.FileField('',blank=True, null=True, help_text='.key llave generada atravez del CSD', upload_to=path_cfdi_company)
    password = models.CharField('', blank=True, null=True, max_length=50, help_text="Contraseña de la llave privada")

    nocertificado = models.CharField('', blank=True, null=True, max_length=50, help_text="Numero de certificado")

    estatus = models.CharField(choices=FiscalData_estatus, max_length=255, blank=True, null=True)

    active = models.BooleanField(default=True)

    class Meta:
        default_permissions = ()
        verbose_name = VERBOSE_NAME
        verbose_name_plural = VERBOSE_NAME_PLURAL
        permissions = (
            ('can_view_'+ MODEL.lower(), 'Ve lista de '+ VERBOSE_NAME_PLURAL.lower()),
            ('can_edit_'+ MODEL.lower(), 'Modifica '+ VERBOSE_NAME_PLURAL.lower()),
            ('can_create_'+ MODEL.lower(), 'Crea '+ VERBOSE_NAME_PLURAL.lower()),
            ('can_delete_'+ MODEL.lower(), 'Elimina '+ VERBOSE_NAME_PLURAL.lower()),
        )

    def __str__(self):
        return self.rfc

    def string(self):
        return mark_safe("""
            {0} {1} <br />
            <strong>Persona {2}</strong> Estatus: 
            """.format(self.rfc, self.razon_social, self.persona))

    def save_certs(self, action):
        if settings.VAR_PRODUCTION['PRODUCTION']:
            s3 = boto3.resource('s3', aws_access_key_id=settings.VAR_PRODUCTION['VAR_DJANGO_AWS_ACCESS_KEY_ID'], aws_secret_access_key=settings.VAR_PRODUCTION['VAR_AWS_SECRET_ACCESS_KEY'])
            bucket = s3.Bucket(settings.VAR_PRODUCTION['VAR_AWS_STORAGE_BUCKET_NAME'])
            directory = "invoice/certificados/%s_%s/%s/" % (self.company.id, self.company.name, self.rfc)
            if not os.path.exists(directory):
                os.makedirs(directory)
            bucket.download_file('media/'+self.cer.name, directory+self.rfc+'.cer')
            bucket.download_file('media/'+self.key.name, directory+self.rfc+'.key')
        else:
            directory = "media/companys/%s_%s/certificados/%s/" % (self.company.id, self.company.name, self.rfc)
        client = zeep.Client(wsdl='https://facturacion.finkok.com/servicios/soap/registration.wsdl')
        if action == 'add':
            client.service.add( 
                reseller_username = settings.VAR_PRODUCTION['INVOICE_USER'], 
                reseller_password = settings.VAR_PRODUCTION['INVOICE_PASSWORD'], 
                taxpayer_id = self.rfc, 
                type_user = 'O', 
                added = datetime.datetime.now().strftime('%Y-%m-%dT%H:%M:%S'),
                cer = open(directory+self.rfc+'.cer', "rb").read(),
                key = open(directory+self.rfc+'.key', "rb").read(),
                passphrase = self.password,
            )
        else:
            client.service.edit(
                reseller_username = settings.VAR_PRODUCTION['INVOICE_USER'],
                reseller_password = settings.VAR_PRODUCTION['INVOICE_PASSWORD'],
                taxpayer_id = self.rfc, 
                cer = open(directory+self.rfc+'.cer', "rb").read(),
                key = open(directory+self.rfc+'.key', "rb").read(),
                passphrase = self.password,
                status = 'A',
            )
        respuesta = directory.replace(" ","\ ")+self.rfc+'.cer'
        nocertificado = os.popen('openssl x509 -inform DER -in '+respuesta+' -noout -serial').readlines()[0].replace("serial=","").replace("\n","")
        self.nocertificado = "" 
        for i in range(len(nocertificado)):
            if i % 2 != 0:
                self.nocertificado = self.nocertificado + nocertificado[i]
        self.save()
        return True

    def add_text(self):
        return "NUEVA "+ self.VERBOSE_NAME.upper(), "Agregar "+ self.VERBOSE_NAME.lower(), "Agrega "+self.GENDER_NEW+" "+ self.VERBOSE_NAME.lower() +" en el sistema"

    def edit_text(self):
        return "EDITAR "+ self.VERBOSE_NAME.upper(), "Editar "+ self.VERBOSE_NAME.lower(), "Edita los datos de "+self.GENDER_THIS+" "+self.VERBOSE_NAME.lower()+" en el sistema"

    def delete_text(self):
        return "ELIMINAR "+ self.VERBOSE_NAME.upper(), "Eliminar "+ self.VERBOSE_NAME.lower(), "Elimina los datos de "+self.GENDER_THIS+" "+self.VERBOSE_NAME.lower(),"Se eliminará "+self.GENDER_THIS+" "+self.VERBOSE_NAME.lower()+" y todos sus datos asociados!"

    def get_absolute_url_list(self):
        return reverse(APP+':'+self.MODEL.lower()+'-list')

    def get_absolute_url_add(self):
        return reverse(APP+':'+self.MODEL.lower()+'-add')

    def get_absolute_url_detail(self):
        return reverse(APP+':'+self.MODEL.lower()+'-detail',kwargs={'pk': self.pk})

invoice/forms.py
# -*- encoding: utf-8 -*-
from django import forms
from django.forms import widgets
from project.forms import MaterialCheckboxWidget, MaterialDateWidget, MaterialTextWidget, SelectWidget, SelectMultipleWidget, MaterialColorWidget
from .models import *

class FiscalDataForm(forms.ModelForm):
	class Meta:
		model = FiscalData
		fields = ('rfc','razon_social','persona','password','cer','key','curp','telefono','contacto','email_contacto','calle','numero_exterior','numero_interior','colonia','localidad','municipio_delegacion','estado','codigo_postal',)
		widgets={
			'estado':SelectWidget(attrs={'class':'select2',}),
			'persona':SelectWidget(attrs={'class':'select2','data-minimum-results-for-search':'Infinity'}),
			'password':MaterialTextWidget(attrs={'class':'form-control','required':'required','type':'password'}),
		}

magicproseries/invoice/forms.py
# -*- encoding: utf-8 -*-
from django import forms
from django.forms import widgets
from project.forms import MaterialCheckboxWidget, MaterialDateWidget, MaterialTextWidget, SelectWidget, SelectMultipleWidget, MaterialColorWidget
from .models import *

class FiscalDataForm(forms.ModelForm):
	class Meta:
		model = FiscalData
		fields = ('rfc','razon_social','persona','password','cer','key','curp','telefono','contacto','email_contacto','calle','numero_exterior','numero_interior','colonia','localidad','municipio_delegacion','estado','codigo_postal',)
		widgets={
			'estado':SelectWidget(attrs={'class':'select2',}),
			'persona':SelectWidget(attrs={'class':'select2','data-minimum-results-for-search':'Infinity'}),
			'password':MaterialTextWidget(attrs={'class':'form-control','required':'required','type':'password'}),
		}

magicproseries/invoice/templates/fiscaldata_create.html
{% extends "generic/create.html" %}
{% load static%}
{% load crispy_forms_tags %}
{% load app_tags%}

{%block rules%}
    rfc: {
        required : true,
    },
    razon_social: {
        required : true,
    },
{%endblock rules%} 

{%block extend_vue_Data%}
    persona: 'Física',
{%endblock extend_vue_Data%}


{%block extend_vue_watch%}
    'persona': function(val, oldVal){
        if (val == 'Física'){
            $('#div_id_curp').show()
            $('#id_curp').val('')
        }
        else{
             $('#div_id_curp').hide()
        }
    },
{%endblock extend_vue_watch%}

{%block extend_vue_mounted%}
    {{ block.super }}
    $("#id_telefono").mask('(00) 0000 0000')
{%endblock extend_vue_mounted%}

magicproseries/invoice/templates/fiscaldata_detail.html
{% extends "generic/detail.html" %}
{% load static%}
{% load crispy_forms_tags %}
{% load app_tags%}


{%block more_options%}
{%endblock%}

{%block detail_grid%}
    <div class="grid-margins-items" size="2">
        <div class="stats__item">
            <div class="stats__chart bg-default">
                <h2 class="color-1 fs-18 mb-0">{{object|upper}}</h2>
            </div>
            <div class="stats__info">
                <div class="row stats grid">
                    <div class="grid-item">
                        <div class="listview listview--inverse listview--striped">
                            {%if object.rfc %}
                                <div class="listview__item lh-9">
                                    <div class="widget-past-days__info">
                                        <h3 class="color-default fs-14 mb-0">{{object.rfc}}</h3>
                                        <small class="color-5 mt-3 fs-9">RFC</small>
                                    </div>
                                </div>
                            {%endif%}
                            {%if object.razon_social %}
                                <div class="listview__item lh-9">
                                    <div class="widget-past-days__info">
                                        <h3 class="color-default fs-14 mb-0">{{object.razon_social}}</h3>
                                        <small class="color-5 mt-3 fs-9">RAZÓN SOCIAL</small>
                                    </div>
                                </div>
                            {%endif%}
                            {%if object.persona %}
                                <div class="listview__item lh-9">
                                    <div class="widget-past-days__info">
                                        <h3 class="color-default fs-14 mb-0">{{object.persona}}</h3>
                                        <small class="color-5 mt-3 fs-9">TIPO DE PERSONA</small>
                                    </div>
                                </div>
                            {%endif%}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{%endblock detail_grid%}

magicproseries/invoice/templates/fiscaldata_list.html
{% extends "generic/list.html" %}
{% load static%}

{%block list%}
    <thead>
        <tr>
            <th>RFC</th>
            <th>RAZON SOCIAL</th>
            <th>PERSONA</th>
            <th>CERTIFICADO</th>
            <th>CONTACTO</th>
            <th>EMAIL CONTACTO</th>
            <th>ESTATUS</th>
        </tr>
    </thead>
    <tbody>
        {%for obj in object_list%}
            <tr>
                <td><a href="{{obj.get_absolute_url_detail}}" class="color-default">{{obj.rfc}}</a></td>
                <td><a href="{{obj.get_absolute_url_detail}}" class="color-default">{{obj.razon_social}}</a></td>
                <td><a href="{{obj.get_absolute_url_detail}}" class="color-default">{{obj.persona}}</a></td>
                <td><a href="{{obj.get_absolute_url_detail}}" class="color-default">{{obj.nocertificado}}</a></td>
                <td><a href="{{obj.get_absolute_url_detail}}" class="color-default">{{obj.contacto|default:"-"}}</a></td>
                <td><a href="{{obj.get_absolute_url_detail}}" class="color-default">{{obj.email_contacto|default:"-"}}</a></td>
                <td>
                    <a href="{{obj.get_absolute_url_detail}}" class="color-default">
                        {%if obj.estatus == 'success'%}
                            <i class="fa fa-circle color-success"></i>
                        {%elif  obj.estatus == 'danger'%}
                            <i class="fa fa-circle color-danger"></i>
                        {%else%}
                            <i class="fa fa-circle color-warning"></i>
                        {%endif%}
                    </a>
                </td>
            </tr>
        {%endfor%}
    </tbody>
{%endblock list%}s

magicproseries/invoice/templates/invoice_ticket.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=.8, shrink-to-fit=no, user-scalable=no">
        <title>{% block title %}FACTURACION{% endblock title %} :: {{VAR.VAR_LOCAL.NAME}}</title>
        <link href="{{VAR.STATIC_URL}}{{VAR.VAR_LOCAL.ICO}}" rel="icon" type="image/x-icon" />
        <meta name="description" content="{{VAR.VAR_LOCAL.PAGES.DESCRIPTION}}">
        <link rel="stylesheet" href="{%static 'vendors/bower_components/material-design-iconic-font/dist/css/material-design-iconic-font.min.css'%}">
        <link rel="stylesheet" href="{%static 'vendors/bower_components/animate.css/animate.min.css'%}">
        <link rel="stylesheet" href="{{VAR.VAR_GLOBAL.FONT_AWESOME}}">
        <link rel="stylesheet" href="{%static 'vendors/bower_components/sweetalert2/dist/sweetalert2.min.css'%}">
        <link rel="stylesheet" href="{%static 'css/app.min.css'%}">
    </head>
    {% include "include/globalstyle.html" %}
    {% include "include/login_style.html" %}
    <body data-ma-theme="green" class="bg-color-default">
        <div class="login">
            <div class="login__block active" id="l-login">
                <div class="login__block__header">
                    <i class="zmdi zmdi-collection-pdf"></i>
                    <strong>EMISIÓN DE FACTURAS</strong> 
                </div>
                <form class="form" method="post" enctype="multipart/form-data" action="{%url 'invoice:invoice_ticket'%}">{% csrf_token %}
                    <div class="login__block__body">
                        <div class="form-group form-group--float form-group--centered">
                            <input type="text" class="form-control" name="folio">
                            <label>Ingresa el FOLIO de tu ticket</label>
                            <i class="form-group__bar"></i>
                        </div>
                        <div class="form-group form-group--float form-group--centered">
                            <input type="password" class="form-control re-type" name="key">
                            <label>Ingresa el KEY de tu ticket</label>
                            <i class="form-group__bar"></i>
                        </div>
                        <div class="form-group form-group--float form-group--centered">
                            <input type="text" class="form-control re-type" name="rfc">
                            <label>Tu RFC</label>
                            <i class="form-group__bar"></i>
                        </div>
                        <div class="form-group form-group--float form-group--centered">
                            <input type="text" class="form-control re-type" name="name">
                            <label>Tu Razón Social</label>
                            <i class="form-group__bar"></i>
                        </div>
                        <div class="form-group form-group--float form-group--centered">
                            <input type="text" class="form-control re-type" name="email">
                            <label>Tu EMAIL</label>
                            <i class="form-group__bar"></i>
                        </div>
                        <button class="btn btn--icon login__block__btn btn_form btn-color-primary" type="submit"><i class="zmdi zmdi-long-arrow-right"></i></button>
                    </div>
                    <small class="pull-right fs-9 color-1">{{VAR.DOMAIN|upper}}</small>
                </form>
            </div>
        </div>
        <script src="{%static 'vendors/bower_components/jquery/dist/jquery.min.js'%}"></script>
        <script src="{%static 'vendors/bower_components/tether/dist/js/tether.min.js'%}"></script>
        <script src="{%static 'vendors/bower_components/bootstrap/dist/js/bootstrap.min.js'%}"></script>
        <script src="{%static 'vendors/bower_components/Waves/dist/waves.min.js'%}"></script>
        <script src="{%static 'vendors/bower_components/sweetalert2/dist/sweetalert2.min.js'%}"></script>
        <script src="{%static 'js/filesaver.js'%}"></script>
        <script src="{%static 'js/app.min.js'%}"></script>
        <script>
            $( ".form" ).submit(function( e ) {
                e.preventDefault();
                $('.btn_form').attr('disabled','disabled');
                var $form = $(e.target)
                $.ajax({
                    async : true,
                    type: "POST",
                    url: $form.attr('action'),
                    data: $form.serialize(),
                    success: function(json){
                        $('.btn_form').removeAttr('disabled');
                        if (!json.api){
                            swal({
                                title: "Oooopsss!",
                                text: json.message,
                                buttonsStyling: false,
                                confirmButtonClass: 'btn btn-inverse btn-color-inverse'
                            })
                            //$('login_password')
                            //$(".re-type").val('')
                        }
                        else{
                            var content = json.api.xml;
                            var filename = json.api.uuid+'.xml';
                            var blob = new Blob([content], {
                             type: "text/plain;charset=utf-8"
                            });
                            saveAs(blob, filename);
                            swal({
                                title: "MUCHAS GRACIAS!",
                                text: json.message,
                                buttonsStyling: false,
                                confirmButtonClass: 'btn btn-inverse btn-color-inverse'
                            })
                            //$('login_password')
                            //$(".re-type").val('')
                        }
                    },
                    error: function(json){
                        swal({
                            title: "Algo salió mal!",
                            text: "Contacta a un administrador para solucionar este problema.",
                            buttonsStyling: false,
                            confirmButtonClass: 'btn btn-danger btn-color-danger'
                        })
                        $('.btn_form').removeAttr('disabled');
                        //$(".re-type").val('')
                    },
                });
            });
        </script>
    </body>
</html>